plugins/kubernetes/config/routes.rb
Samson::Application.routes.draw do
  resources :projects do
    namespace :kubernetes do
      resources :roles, except: :edit do
        collection do
          post :seed
          get :example
        end
      end
      resources :releases, only: [:index]
    end
  end

  namespace :kubernetes do
    resource :role_verification, only: [:new, :create]
  end

  namespace :admin do
    namespace :kubernetes do
      resources :clusters, except: :destroy
      resources :deploy_group_roles do
        collection do
          post :seed
        end
      end
    end
  end
end

plugins/kubernetes/app/views/samson_kubernetes/_admin_menu.html.erb
<li><%= link_to "Kubernetes Clusters", admin_kubernetes_clusters_path %></li>
<li><%= link_to "Kubernetes Roles", admin_kubernetes_deploy_group_roles_path %></li>

plugins/kubernetes/app/views/samson_kubernetes/_build_new.erb
<div class="form-group">
  <%= form.label :kubernetes_job, "Use Remote Kubernetes Job?", class: "col-lg-2 control-label" %>
  <div class="col-lg-4">
    <%= form.check_box :kubernetes_job %>
  </div>
</div>

plugins/kubernetes/app/views/samson_kubernetes/_deploy_group_form.html.erb
<%= form.fields_for :cluster_deploy_group, include_id: false do |cluster_form| %>
  <div class="form-group">
    <%= cluster_form.label :kubernetes_cluster_id, "Kubernetes Cluster", class: "col-lg-2 control-label" %>
    <div class="col-lg-4">
      <%= cluster_form.collection_select(:kubernetes_cluster_id, Kubernetes::Cluster.all, :id, :name, { include_blank: true }, { class: 'form-control' }) %>
    </div>
  </div>

  <div class="form-group">
    <%= cluster_form.label :namespace, "Kubernetes Namespace", class: "col-lg-2 control-label" %>
    <div class="col-lg-4">
      <%= cluster_form.text_field :namespace, class: "form-control" %>
    </div>
  </div>
<% end %>

plugins/kubernetes/app/views/samson_kubernetes/_deploy_group_show.html.erb
<div class="form-group">
  <label class="col-lg-2 control-label">Kubernetes Cluster</label>
  <div class="col-lg-4">
    <p class="form-control-static">
      <% if @deploy_group.kubernetes_cluster %>
        <%= link_to @deploy_group.kubernetes_cluster.name, [:admin, @deploy_group.kubernetes_cluster] %>
      <% else %>
        none
      <% end %>
    </p>
  </div>
</div>

<div class="form-group">
  <label class="col-lg-2 control-label">Kubernetes Namespace</label>
  <div class="col-lg-4">
    <p class="form-control-static"><%= @deploy_group.kubernetes_namespace %></p>
  </div>
</div>

plugins/kubernetes/app/views/samson_kubernetes/_deploy_group_table_cell.html.erb
<td><%= link_to(deploy_group.kubernetes_cluster.name, admin_kubernetes_cluster_path(deploy_group.kubernetes_cluster)) if deploy_group.kubernetes_cluster %></td>

plugins/kubernetes/app/views/samson_kubernetes/_deploy_group_table_header.html.erb
<th>Kubernetes Cluster</th>

plugins/kubernetes/app/views/samson_kubernetes/_deploy_tab_body.html.erb
<% if @deploy.kubernetes && @deploy.kubernetes_release %>
  <% release = @deploy.kubernetes_release %>
  <div class="tab-pane" id="kubernetes_release">
    <h2>Release #<%= @deploy.kubernetes_release.id %></h2>
    GIT: <%= release.git_ref %> @ <%= release.git_sha %><br/>

    <h3>Release docs</h3>
    <% release.release_docs.sort_by { |rd| rd.deploy_group.natural_order }.each do |release_doc| %>
      <div>
        <h3><%= release_doc.deploy_group.name %> - <%= link_to release_doc.kubernetes_role.name, [@project, release_doc.kubernetes_role] %></h3>
        <pre><%= release_doc.resource_template.to_yaml %></pre>
      </div>
    <% end %>
  </div>
<% end %>

plugins/kubernetes/app/views/samson_kubernetes/_deploy_tab_nav.html.erb
<% if @deploy.kubernetes && @deploy.kubernetes_release %>
  <li><a href="#kubernetes_release" data-toggle="tab">Release docs</a></li>
<% end %>

plugins/kubernetes/app/views/samson_kubernetes/_navigation.html.erb
<% links = [
  ["Roles", project_kubernetes_roles_path],
  ["Releases", project_kubernetes_releases_path]
] %>

<ul class="nav nav-tabs">
  <% links.each do |name, path| %>
    <% active = request.path.start_with?(path) %>
    <li class="<%= "active" if active %>"><%= link_to name, active ? '#' : path %></li>
  <% end %>
</ul>

plugins/kubernetes/app/views/samson_kubernetes/_project_tab.html.erb
<li class="<%= 'active' if active == 'kubernetes' %>">
  <%= link_to project_kubernetes_releases_path(project), style: 'padding-top: 10px; padding-bottom: 10px' do %>
    <%= image_tag('kubernetes/icon.png', height: '30px') %>
  <% end %>
</li>

plugins/kubernetes/app/views/samson_kubernetes/_stage_form.html.erb
<fieldset>
  <legend>Kubernetes</legend>
  <div class="col-lg-6 checkbox col-lg-offset-2">
    <%= form.label 'Kubernetes', for: nil do %>
      <%= form.check_box :kubernetes, id: 'stage_kubernetes' %>
      Deploy via kubernetes / ignore commands.
    <% end %>
  </div>
</fieldset>

<script>
  $(function(){
    // hide command section when kubernetes is selected
    var $checkbox = $("#stage_kubernetes");
    $checkbox.change(function(){
      $("#commands").parent('fieldset').toggle(!$(this).is(':checked'))
    });
    $checkbox.trigger('change');
  });
</script>

plugins/kubernetes/app/views/samson_kubernetes/_stage_show.html.erb
<% if @stage.kubernetes %>
  <h2><%= link_to "Kubernetes Roles", project_kubernetes_roles_path(@stage.project) %></h2>

  <% matrix = Kubernetes::DeployGroupRole.matrix(@stage) %>
  <% project_dg_roles = matrix.flat_map(&:last).map!(&:last) %>
  <% missing = project_dg_roles.include?(nil) %>

  <table class="table table-hover table-condensed">
    <thead>
      <th>Deploy Group</th>
      <th>Replicas</th>
      <th>CPU</th>
      <th>RAM</th>
      <th>
        <% if missing %>
          <%= link_to 'Seed Missing', seed_admin_kubernetes_deploy_group_roles_path(stage_id: @stage.id), data: {method: :post} %>
        <% end %>
      </th>
    </thead>

    <% matrix.each do |deploy_group, roles| %>
      <tr>
        <td colspan="5"><h3><%= deploy_group.name %></h3></td>
      </tr>
      <% roles.each do |role, dg_role| %>
        <tr>
          <td><%= role.name %></td>
          <% if dg_role %>
            <td><%= dg_role.replicas %></td>
            <td><%= dg_role.cpu %></td>
            <td><%= dg_role.ram %></td>
            <td>
              <% if current_user.admin_for?(@stage.project) %>
                <%= link_to 'Edit', edit_admin_kubernetes_deploy_group_role_path(dg_role) %>
              <% end %>
            </td>
          <% else %>
            <td colspan="3">Missing</td>
            <td>
              <% if current_user.admin_for?(@stage.project) %>
                <% attributes = {kubernetes_role_id: role.id, project_id: @stage.project_id, deploy_group_id: deploy_group.id} %>
                <%= link_to "Create", new_admin_kubernetes_deploy_group_role_path(kubernetes_deploy_group_role: attributes, redirect_to: request.path) %>
              <% end %>
            </td>
          <% end %>
        </tr>
      <% end %>

      <% dg_roles = roles.map(&:last).compact %>
      <tr>
        <td>Subtotal</td>
        <td><%= dg_roles.sum(&:replicas) %></td>
        <td><%= dg_roles.sum { |gr| gr.cpu * gr.replicas } %></td>
        <td><%= dg_roles.sum { |gr| gr.ram * gr.replicas } %></td>
        <td></td>
      </tr>
    <% end %>

    <tr>
      <td><b>Total</b></td>
      <% found_roles = project_dg_roles.compact %>
      <td><%= found_roles.sum(&:replicas) %></td>
      <td><%= found_roles.sum { |gr| gr.cpu * gr.replicas } %></td>
      <td><%= found_roles.sum { |gr| gr.ram * gr.replicas } %></td>
      <td></td>
    </tr>
  </table>

  <script>
    $(function(){
      // hide command section when kubernetes is selected
      $("#script-section").hide();

      // disable Deploy button when roles are missing and deploy would fail
      var title = (<%= missing %> ? "A kubernetes role is missing!" : "")
      $(".btn-primary").toggleClass('disabled', <%= missing %>).attr('title', title);
    });
  </script>
<% end %>