config/routes.rb
Samson::Application.routes.draw do
  use_doorkeeper
  root to: 'projects#index'

  namespace :api do
    resources :deploys, only: [:index, :active_count] do
      collection do
        get :active_count
      end
    end

    resources :stages, only: [:index] do
      post :clone, to: 'stages#clone'
    end
  end

  resources :projects do
    resources :jobs, only: [:index, :new, :create, :show, :destroy]

    resources :macros, only: [:index, :new, :create, :edit, :update, :destroy] do
      member { post :execute }
    end

    resources :builds, only: [:show, :index, :new, :create, :edit, :update] do
      member do
        post :build_docker_image
      end
    end

    resources :deploys, only: [:index, :show, :destroy] do
      collection do
        get :active
      end

      member do
        post :buddy_check
        get :changeset
      end
    end

    resources :releases, only: [:show, :index, :new, :create]

    resources :stages do
      collection do
        patch :reorder
      end

      member do
        get :clone, to: 'stages#clone'
      end

      resources :deploys, only: [:new, :create] do
        collection do
          post :confirm
        end
      end
    end

    resource :changelog, only: [:show]
    resources :webhooks, only: [:index, :create, :destroy]
    resource :commit_statuses, only: [:show]
    resources :references, only: [:index]

    resources :users, only: [:index, :update]

    resources :project_roles, only: [:create]

    member do
      get :deploy_group_versions
    end
  end

  resources :streams, only: [:show]
  resources :locks, only: [:create, :destroy]

  resources :deploys, only: [:index] do
    collection do
      get :active
      get :recent
      get :search
    end
  end

  resources :deploy_groups, only: [:show]

  resource :profile, only: [:show, :update]

  resources :versions, only: [:index]

  get '/auth/github/callback', to: 'sessions#github'
  get '/auth/google/callback', to: 'sessions#google'
  post '/auth/ldap/callback', to: 'sessions#ldap'
  get '/auth/gitlab/callback', to: 'sessions#gitlab'
  get '/auth/failure', to: 'sessions#failure'

  get '/jobs/enabled', to: 'jobs#enabled', as: :enabled_jobs

  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'

  resources :csv_exports, only: [:index, :new, :create, :show]
  resources :stars, only: [:create, :destroy]
  resources :dashboards, only: [:show] do
    member do
      get :deploy_groups
    end
  end

  namespace :admin do
    resources :users, only: [:index, :show, :update, :destroy]
    resource :projects, only: [:show]
    resources :commands, except: [:show]
    resources :secrets, except: [:show]
    resources :environments, except: [:show]
    resources :deploy_groups do
      member do
        get :deploy_all
        post :deploy_all_now
      end
    end
  end

  namespace :integrations do
    post "/circleci/:token" => "circleci#create", as: :circleci_deploy
    post "/travis/:token" => "travis#create", as: :travis_deploy
    post "/semaphore/:token" => "semaphore#create", as: :semaphore_deploy
    post "/tddium/:token" => "tddium#create", as: :tddium_deploy
    post "/jenkins/:token" => "jenkins#create", as: :jenkins_deploy
    post "/buildkite/:token" => "buildkite#create", as: :buildkite_deploy
    post "/github/:token" => "github#create", as: :github_deploy
  end

  get '/ping', to: 'ping#show'

  resources :access_requests, only: [:new, :create]

  mount SseRailsEngine::Engine, at: '/streaming'
end

app/models/user.rb
require 'soft_deletion'
require 'digest/md5'

class User < ActiveRecord::Base
  include Searchable
  include HasRole

  TIME_FORMATS = ['local', 'utc', 'relative'].freeze

  has_soft_deletion default_scope: true

  has_paper_trail skip: [:updated_at, :created_at, :token]

  has_many :commands
  has_many :stars
  has_many :locks, dependent: :destroy
  has_many :user_project_roles, dependent: :destroy
  has_many :projects, through: :user_project_roles
  has_many :csv_exports, dependent: :destroy

  validates :role_id, inclusion: { in: Role.all.map(&:id) }

  before_create :set_token
  validates :time_format, inclusion: { in: TIME_FORMATS }

  scope :search, ->(query) {
    return self if query.blank?
    query = ActiveRecord::Base.send(:sanitize_sql_like, query)
    where("name LIKE ? OR email LIKE ?", "%#{query}%", "%#{query}%")
  }
  scope :with_role, -> (role_id, project_id) {
    joins("LEFT OUTER JOIN user_project_roles ON users.id = user_project_roles.user_id AND user_project_roles.project_id = #{project_id.to_i}"). # rubocop:disable Metrics/LineLength
      where('users.role_id >= ? OR user_project_roles.role_id >= ?', role_id, role_id)
  }

  def starred_project?(project)
    starred_project_ids.include?(project.id)
  end

  def starred_project_ids
    Rails.cache.fetch([:starred_projects_ids, id]) do
      stars.pluck(:project_id)
    end
  end

  # returns a scope
  def administrated_projects
    scope = Project.order(:name)
    unless admin?
      allowed = user_project_roles.where(role_id: Role::ADMIN.id).pluck(:project_id)
      scope = scope.where(id: allowed)
    end
    scope
  end

  def self.create_or_update_from_hash(hash)
    user = User.where(external_id: hash[:external_id].to_s).first || User.new

    # attributes are always a string hash
    attributes = user.attributes.merge(hash.stringify_keys) do |key, old, new|
      if key == 'role_id'
        if !User.exists? # first user will be the super admin
          Role::SUPER_ADMIN.id
        elsif new && (user.new_record? || new >= old)
          new
        else
          old
        end
      else
        old.presence || new
      end
    end

    user.attributes = attributes
    user.save
    user
  end

  def name
    super.presence || email
  end

  def name_and_email
    "#{name} (#{email})"
  end

  def gravatar_url
    md5 = email.blank? ? "default" : Digest::MD5.hexdigest(email)
    "https://www.gravatar.com/avatar/#{md5}"
  end

  def admin_for?(project)
    admin? || !!project_role_for(project).try(:admin?)
  end

  def deployer_for?(project)
    deployer? || !!project_role_for(project).try(:deployer?)
  end

  def project_role_for(project)
    user_project_roles.find_by(project: project)
  end

  def record_project_role_change
    record_update true
  end

  private

  # overwrites papertrail to record script
  def object_attrs_for_paper_trail(attributes)
    roles = user_project_roles.map { |upr| [upr.project.permalink, upr.role_id] }.to_h
    super(attributes.merge('project_roles' => roles))
  end

  def set_token
    self.token = SecureRandom.hex
  end
end

app/views/shared/_alerts.html.erb
<% flash_messages.each do |type, klass, message| %>
  <div class="alert alert-<%= klass %>">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= message %>
    <%= link_to_request_access if display_access_request_link?(type) %>
  </div>
<% end %>

<!-- Flash messages for ajax requests -->
<mc-messages></mc-messages>

app/views/shared/_commands.html.erb
<fieldset>
  <legend>Script</legend>
  <p>Select the commands you want to run when executing. Double click to edit commands.</p>

  <div id="commands">
    <% usage_ids = Command.usage_ids %>
    <%= form.collection_check_boxes(:command_ids, Command.for_object(form.object), :id, :command) do |b| %>
      <% command = b.object %>
      <% others = usage_ids.count(command.id) - (b.check_box.include?('checked') && form.object.persisted? ? 1 : 0) %>
      <% others_warning = "#{others} others" if others > 0 %>

      <div class="row stage-bar bar">
        <div data-id="<%= b.value %>" class="col-lg-offset-2 col-lg-2 command-checkbox">
          <%= b.check_box %>
        </div>
        <div class="col-lg-8">
          <% klass = "pre-command pre-inline #{command.global? ? 'global' : 'local'} #{'others' if others_warning}" %>
          <pre data-type="textarea" data-others-warning="<%= others_warning %>" data-url="<%= admin_command_path(b.value, format: :json) %>" class="<%= klass %>"><%= b.text %></pre>
        </div>
        <%= edit_command_link command %>
        <%= content_tag :span, others, title: others_warning + " use this. Click edit for details.", class: 'glyphicon glyphicon-lock' if others_warning %>
      </div>
    <% end %>
  </div>

  <hr />

  <p>Add a command which is specific to your project</p>
  <%= form.text_area :command, class: "form-control", rows: 4, value: nil, placeholder: 'cap production deploy' %>
</fieldset>

<script>
  $(function() {
    var $localCommands = $('#commands pre.local');

    $('#commands').sortable();
    $.fn.editableform.buttons = <%= render('commands/buttons').inspect.html_safe %>;

    $localCommands.editable({
      mode: 'inline',
      send: 'always',
      toggle: 'dblclick',
      highlight: false,
      params: function(params) {
        return { command: { command: params.value } };
      },
      ajaxOptions: {
        type: 'PATCH',
        dataType: 'json'
      }
    });

    $localCommands.filter(".others").dblclick(function(){
      alert("Editing for " + $(this).data('others-warning') + ". If you do not want this, make a copy.");
    });

    $('#commands pre.global').dblclick(function(){
      var $warning = $('<div class="cannot-edit">Global commands cannot be edited inline, use the Admin UI.</div>')
      $(this).after($warning);
      $warning.fadeOut(3000);
      return false;
    });

    $('#commands').on('click', '.editable-destroy', function(event) {
      var editable = $(this).closest('div.col-lg-8').children('.pre-command');

      if(confirm('Are you sure you would like to remove this command from all stages?')) {
        $.ajax({
          method: 'DELETE',
          dataType: 'json',
          url: editable.data('url'),
          success: function() {
            editable.closest('.row').fadeOut();
          }
        });
      }

      event.preventDefault();
    });
  });
</script>

app/views/shared/_deploys_table.html.erb
<section class="tabs">
  <table class="table">
    <thead>
      <tr>
        <% unless @project %>
          <th>Project</th>
        <% end %>

        <th>When</th>
        <th>Who</th>
        <% unless @stage %>
          <th>Stage</th>
        <% end %>
        <th>Status</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= render partial: "/projects/deploy", collection: @deploys %>
    </tbody>
  </table>

  <%= paginate @deploys if @deploys.respond_to?(:total_pages) %>
</section>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div class="row">
    <div class="col-lg-5 col-lg-offset-1 alert alert-warning">
      <p><strong>Ooops!</strong> There was an error:</p>
      <%= render_nested_errors(object) %>
    </div>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="container">
    <div class="links">

      <div class="pull-left">
        Built by Zendesk
      </div>

      <div class="pull-right">
      <% if revision %>
        <span class="sha">
          <%= link_to "https://github.com/zendesk/samson/commit/#{revision}",
              title: "Samson release commit", class: "sha" do %>
            <%= revision[0..7] %>
            <i class="glyphicon glyphicon-circle-arrow-right"></i>
          <% end %>
        </span>
      <% end %>
      </div>

    </div>
  </div>
</div>

app/views/shared/_github_link.html.erb
<%= link_to project.repository_homepage, class: "github", target: "_blank", title: "View repository on GitHub" do %>
  <i class="fa fa-github"></i>
<% end %>

app/views/shared/_gitlab_link.html.erb
<%= link_to project.repository_homepage, class: "gitlab", target: "_blank", title: "View repository on Gitlab" do %>
  <%= image_tag "gitlab.png", width: 21, height: 21 %>
<% end %>

app/views/shared/_header.html.erb
<div class="navbar navbar-inverse">
  <div class="container">
    <%= link_to "Samson", root_path, class: "navbar-brand" %>

    <ul class="nav navbar-nav">
      <% if current_user %>
        <li class="dropdown <%= 'active' if request.path.starts_with?('/projects') %>">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" focus-on="{ click: '#project_search' }">Projects <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li>
              <a class="padding-sm">
                <input id="project_search" type="search" handle-dropdown-selection class="filter-list form-control input-block" placeholder="Search projects" data-target=".filtered-projects">
              </a>
            </li>
            <li class="divider"></li>
            <% Project.ordered_for_user(current_user).each do |project| %>
              <li class="filtered-projects">
                <%= link_to project do %>
                  <% starred = current_user.starred_project?(project) %>
                  <span class="glyphicon <%= 'glyphicon-star' if starred %>">
                    <%= '&nbsp;'.html_safe unless starred %>
                  </span>
                  <%= project.name %>
                <% end %>
              </li>
            <% end %>
          </ul>
        </li>
        <% if DeployGroup.enabled? %>
          <li class="dropdown <%= 'active' if request.path.starts_with?('/dashboards') %>">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Environments <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <% environments.each do |env| %>
                <li>
                  <%= link_to dashboard_path(env) do %>
                    <span class="glyphicon">&nbsp;</span> <%= env.name %>
                  <% end %>
                </li>
              <% end %>
            </ul>
          </li>
        <% end %>
        <li class="<%= 'active' if current_page?(controller: '/deploys', action: 'search') %>">
          <%= link_to "Deploys", search_deploys_path %>
        </li>
        <li class="current-deploys <%= 'active' if current_page?(controller: '/deploys', action: 'active') %>" ng-controller="currentDeployBadgeCtrl">
          <%= link_to active_deploys_path do %>
            Deploying
            <%= content_tag :span, '{{ currentActiveDeploys }}',
                class: 'badge badge-deploys',
                style: 'display: none',
                id: 'currentDeploysBadge',
                data: {count: Deploy.active_count}
            %>
          <% end %>
        </li>
      <% end %>

      <li class="dropdown <%= 'active' if request.path.starts_with?('/admin') %>">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Manage <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <% if current_user.try(:admin?) %>
            <% if DeployGroup.enabled? %>
              <li><%= link_to "Environments", admin_environments_path %></li>
              <li><%= link_to "Deploy Groups", admin_deploy_groups_path %></li>
            <% end %>
            <li><%= link_to "Projects", admin_projects_path %></li>
            <li><%= link_to "Commands", admin_commands_path %></li>
            <li><%= link_to "Users", admin_users_path %></li>
            <%= Samson::Hooks.render_views(:admin_menu, self) %>
            <li class="divider"></li>
          <% end %>
          <% if current_user.try(:deployer?) %>
            <li><%= link_to "Secrets", admin_secrets_path %></li>
          <% end %>
          <li><%= link_to "Reports", csv_exports_path %></li>
          <li><%= link_to "OAuth Applications", oauth_applications_path %></li>
          <li><%= link_to "OAuth Authorized Applications", oauth_authorized_applications_path %></li>
        </ul>
      </li>
    </ul>

    <ul class="nav navbar-nav pull-right">
      <% if current_user %>
        <li class="dropdown profile">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <%= image_tag current_user.gravatar_url, class: "gravatar" %>
            <%= current_user.name %>
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Profile", profile_path %></li>
            <li><%= link_to "Logout", logout_path %></li>
          </ul>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_notify_buddy_box.html.erb
<%# see _notify_buddy_box in flowdock and slack_webhooks plugins for examples of using this shared template %>
<%= form_tag form_path do %>
  <div class="alert" style="display: none"></div>

  <div class="panel panel-info">
    <div class="panel-heading">
      <h3 class="panel-title"><%= title %></h3>
    </div>
    <div class="panel-body">
      <div class="col-sm-10">
        <div class="mentions-input-box">
          <%= text_area_tag :message, message, id: id_prefix + 'buddy_request_box' %>
        </div>
        <em>This will send a buddy request to the <strong><%= channels %></strong> <%= channel_type %>.</em>
      </div>
      <div class="col-sm-2">
        <%= submit_tag 'Request a Buddy!', class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

<script>
  $(function(){
    var $input = $('#<%= id_prefix %>buddy_request_box');

    // when user hits 'Request', normalize text and submit via ajax
    var $form = $input.parents('form');
    $form.submit(function(e){
      e.preventDefault();

      // normalize mentioned users @[alex](user:1) -> @alex
      $input.mentionsInput('val', function(text){
        $input.val(text.replace(/@\[([^\\]+?)\]\(([^)]+?)\)/g, "@$1"));
      });

      // submit form without leaving the page and show result
      $.ajax({
        url: $form.attr('action'),
        type: $form.attr('method'),
        data: $form.serialize(),
        success: function() {
          $form.find('.alert').addClass('alert-success').text('Message sent!').show()
        },
        error: function(_, _, text) {
          $form.find('.alert').addClass('alert-danger').text('ERROR: ' + text).show()
        }
      });
    });

    // when user types @, show possible user names
    var users = <%= users.to_json.html_safe %>;
    $input.mentionsInput({
      // prefill with what is already there
      defaultValue: $input.val(),

      // when user types after the @ filter down the possible users
      onDataRequest: function (mode, query, callback) {
        var filtered = _.filter(users, function (user) {
          return user.name.toLowerCase().indexOf(query.toLowerCase()) > -1;
        });
        callback.call(this, filtered);
      }
    });
  });
</script>

app/views/shared/_output.html.erb
<div class="output <%= 'hidden' if hide %>">
  <div class="clearfix">
    <div class="btn-toolbar pull-right" id="output-toolbar">
      <div id="output-options" class="btn-group only-active">
        <button class="btn btn-default active" id="output-follow">Follow</button>
        <button class="btn btn-default" id="output-steady">Don't Follow</button>
        <button class="btn btn-default" id="output-grow">Expand</button>
      </div>

      <button class="btn btn-default only-finished" id="output-grow-toggle">Expand</button>
      <%= link_to "Download log", project_deploy_path(@project, deployable, format: :text), class: "btn btn-primary only-finished" %>

      <% if deployable.can_be_stopped_by?(current_user) %>
        <%= stop_button(class: "btn btn-danger only-active") %>
      <% end %>
    </div>
  </div>

  <%= render partial: "jobs/log", locals: { job: job } %>
</div>

app/views/shared/_project_role.html.erb
<%= form_tag project_project_roles_path(project, user_id: user.id), class: 'autosubmit' do %>
  <% options = [['None', nil]] + UserProjectRole::ROLES.map { |r| [r.name, r.id] } %>
  <% options.each do |name, id| %>
    <%= user_project_role_radio user, project, name, id %>
  <% end %>
<% end %>

app/views/shared/_project_tabs.html.erb
<ul class="nav nav-tabs">
  <li class="<%= 'active' if active == 'stages' %>">
    <%= link_to "Stages", project %>
  </li>
  <li class="<%= 'active' if active == 'releases' %>">
    <%= link_to "Releases", project_releases_path(project) %>
  </li>
  <% if project.deploy_with_docker? %>
    <li class="<%= 'active' if active == 'builds' %>">
      <%= link_to "Builds", project_builds_path(project) %>
    </li>
  <% end %>
  <li class="<%= 'active' if active == 'deploys' %>">
    <%= link_to "Deploys", project_deploys_path(project) %>
  </li>
  <li class="<%= 'active' if active == 'jobs' %>">
    <%= link_to "Jobs", project_jobs_path(project) %>
  </li>
  <li class="<%= 'active' if active == 'macros' %>">
    <%= link_to "Macros", project_macros_path(project) %>
  </li>
  <li class="<%= 'active' if active == 'webhooks' %>">
    <%= link_to "Webhooks", project_webhooks_path(project) %>
  </li>
  <li class="<%= 'active' if active == 'changelog' %>">
    <%= link_to "Changelog", project_changelog_path(project) %>
  </li>

  <%= Samson::Hooks.render_views(:project_tabs_view, self, { project: @project, active: active }) %>

  <% if admin_for_project? %>
    <li class="<%= 'active' if active == 'settings' %>">
      <%= link_to "Settings", edit_project_path(project) %>
    </li>
    <li class="<%= 'active' if active == 'users' %>">
      <%= link_to "Users", project_users_path(project) %>
    </li>
  <% end %>
</ul>

app/views/shared/_search_bar.html.erb
<div class="col-md-5 row pull-right search-bar">
  <%= form_tag url, method: 'get', class: 'form-horizontal' do %>
    <%= label_tag :search, 'Search:', class: 'control-label sr-only' %>
    <div class="input-group">
      <%= text_field_tag :search, query, class: 'form-control', placeholder: 'Search' %>
      <span class="input-group-btn">
        <button type="submit" class="btn btn-default" type="button">
          <span class="glyphicon glyphicon-search"></span>
        </button>
      </span>
    </div>
  <% end %>
</div>

app/views/shared/_search_button.html.erb
<div class="col-md-1 clearfix">
  <label>&nbsp;</label>
  <%= submit_tag "Search", class: "btn btn-default form-control" %>
</div>