config/routes.rb
Samson::Application.routes.draw do
  use_doorkeeper
  root to: 'projects#index'

  namespace :api do
    resources :deploys, only: [:index, :active_count] do
      collection do
        get :active_count
      end
    end

    resources :stages, only: [:index] do
      post :clone, to: 'stages#clone'
    end
  end

  resources :projects do
    resources :jobs, only: [:index, :new, :create, :show, :destroy]

    resources :macros, only: [:index, :new, :create, :edit, :update, :destroy] do
      member { post :execute }
    end

    resources :builds, only: [:show, :index, :new, :create, :edit, :update] do
      member do
        post :build_docker_image
      end
    end

    resources :deploys, only: [:index, :show, :destroy] do
      collection do
        get :active
      end

      member do
        post :buddy_check
        get :changeset
      end
    end

    resources :releases, only: [:show, :index, :new, :create]

    resources :stages do
      collection do
        patch :reorder
      end

      member do
        get :clone, to: 'stages#clone'
      end

      resources :deploys, only: [:new, :create] do
        collection do
          post :confirm
        end
      end
    end

    resource :changelog, only: [:show]
    resources :webhooks, only: [:index, :create, :destroy]
    resource :commit_statuses, only: [:show]
    resources :references, only: [:index]

    resources :users, only: [:index, :update]

    resources :project_roles, only: [:create]

    member do
      get :deploy_group_versions
    end
  end

  resources :streams, only: [:show]
  resources :locks, only: [:create, :destroy]

  resources :deploys, only: [:index] do
    collection do
      get :active
      get :recent
      get :search
    end
  end

  resources :deploy_groups, only: [:show]

  resource :profile, only: [:show, :update]

  resources :versions, only: [:index]

  get '/auth/github/callback', to: 'sessions#github'
  get '/auth/google/callback', to: 'sessions#google'
  post '/auth/ldap/callback', to: 'sessions#ldap'
  get '/auth/gitlab/callback', to: 'sessions#gitlab'
  get '/auth/failure', to: 'sessions#failure'

  get '/jobs/enabled', to: 'jobs#enabled', as: :enabled_jobs

  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'

  resources :csv_exports, only: [:index, :new, :create, :show]
  resources :stars, only: [:create, :destroy]
  resources :dashboards, only: [:show] do
    member do
      get :deploy_groups
    end
  end

  namespace :admin do
    resources :users, only: [:index, :show, :update, :destroy]
    resource :projects, only: [:show]
    resources :commands, except: [:show]
    resources :secrets, except: [:show]
    resources :environments, except: [:show]
    resources :deploy_groups do
      member do
        get :deploy_all
        post :deploy_all_now
      end
    end
  end

  namespace :integrations do
    post "/circleci/:token" => "circleci#create", as: :circleci_deploy
    post "/travis/:token" => "travis#create", as: :travis_deploy
    post "/semaphore/:token" => "semaphore#create", as: :semaphore_deploy
    post "/tddium/:token" => "tddium#create", as: :tddium_deploy
    post "/jenkins/:token" => "jenkins#create", as: :jenkins_deploy
    post "/buildkite/:token" => "buildkite#create", as: :buildkite_deploy
    post "/github/:token" => "github#create", as: :github_deploy
  end

  get '/ping', to: 'ping#show'

  resources :access_requests, only: [:new, :create]

  mount SseRailsEngine::Engine, at: '/streaming'
end

app/models/stage.rb
class Stage < ActiveRecord::Base
  include Permalinkable
  include HasCommands

  has_soft_deletion default_scope: true unless self < SoftDeletion::Core

  has_paper_trail skip: [:order, :updated_at, :created_at]

  belongs_to :project, touch: true

  has_many :deploys, dependent: :destroy
  has_many :webhooks, dependent: :destroy

  has_one :lock

  has_many :command_associations, autosave: true, class_name: 'StageCommand', dependent: :destroy
  has_many :commands, -> { order('stage_commands.position ASC') },
    through: :command_associations, auto_include: false

  has_many :deploy_groups_stages
  has_many :deploy_groups, through: :deploy_groups_stages

  default_scope { order(:order) }

  validates :name, presence: true, uniqueness: { scope: [:project, :deleted_at] }

  before_create :ensure_ordering
  after_destroy :destroy_deploy_groups_stages

  def self.reset_order(new_order)
    transaction do
      new_order.each.with_index { |stage_id, index| Stage.update stage_id.to_i, order: index.to_i }
    end
  end

  def self.build_clone(old_stage)
    new(old_stage.attributes.except("id")).tap do |new_stage|
      Samson::Hooks.fire(:stage_clone, old_stage, new_stage)
      new_stage.command_ids = old_stage.command_ids
    end
  end

  def self.unlocked_for(user)
    where("locks.id IS NULL OR locks.user_id = ?", user.id).
    joins("LEFT OUTER JOIN locks ON \
          locks.deleted_at IS NULL AND \
          locks.stage_id = stages.id")
  end

  def self.deployed_on_release
    where(deploy_on_release: true)
  end

  def self.where_reference_being_deployed(reference)
    joins(deploys: :job).where(
      deploys: { reference: reference },
      jobs: { status: Job::ACTIVE_STATUSES }
    )
  end

  def current_deploy
    return @current_deploy if defined?(@current_deploy)
    @current_deploy = deploys.active.first
  end

  def last_deploy
    return @last_deploy if defined?(@last_deploy)
    @last_deploy = deploys.first
  end

  def last_successful_deploy
    return @last_successful_deploy if defined?(@last_successful_deploy)
    @last_successful_deploy = deploys.successful.first
  end

  def locked?
    !!lock && !lock.warning?
  end

  def warning?
    !!lock && lock.warning?
  end

  def locked_for?(user)
    locked? && lock.user != user
  end

  def current_release?(release)
    last_successful_deploy && last_successful_deploy.reference == release.version
  end

  def confirm_before_deploying?
    confirm
  end

  def create_deploy(user, attributes = {})
    deploys.create(attributes.merge(release: !no_code_deployed)) do |deploy|
      deploy.build_job(project: project, user: user, command: script, commit: deploy.reference)
    end
  end

  def currently_deploying?
    current_deploy.present?
  end

  # The next stage for the project. If this is the last stage, returns nil.
  def next_stage
    stages = project.stages.to_a
    stages[stages.index(self) + 1]
  end

  def notify_email_addresses
    notify_email_address.split(";").map(&:strip)
  end

  def send_email_notifications?
    notify_email_address.present?
  end

  def global_name
    "#{name} - #{project.name}"
  end

  def send_github_notifications?
    update_github_pull_requests
  end

  # this logic is replicated in SQL inside of app/jobs/csv_export_job.rb#filter_deploys for report filtering
  # update the SQL query as well when editing this method
  def production?
    if DeployGroup.enabled?
      deploy_groups.empty? ? super : deploy_groups.any? { |deploy_group| deploy_group.environment.production? }
    else
      super
    end
  end

  def deploy_requires_approval?
    BuddyCheck.enabled? && !no_code_deployed? && production?
  end

  def automated_failure_emails(deploy)
    return if !email_committers_on_automated_deploy_failure? && static_emails_on_automated_deploy_failure.blank?
    return unless deploy.failed?
    return unless deploy.user.integration?
    last_deploy = deploys.finished_naturally.prior_to(deploy).first
    return if last_deploy.try(:failed?)

    emails = []

    # static notification
    emails.concat static_emails_on_automated_deploy_failure.to_s.split(/, ?/)

    # authors of commits after last successful deploy
    if email_committers_on_automated_deploy_failure?
      changeset = deploy.changeset_to(last_deploy)
      emails.concat changeset.commits.map(&:author_email).compact
    end

    emails.uniq.presence
  end

  def command_updated_at
    [
      command_associations.maximum(:updated_at),
      commands.maximum(:updated_at)
    ].compact.max
  end

  def record_script_change
    record_update true
  end

  def destroy
    mark_for_destruction
    super
  end

  def deploy_group_names
    DeployGroup.enabled? ? deploy_groups.select(:name).sort_by(&:natural_order).map(&:name) : []
  end

  private

  def permalink_base
    name
  end

  def permalink_scope
    Stage.unscoped.where(project_id: project_id)
  end

  def ensure_ordering
    return unless project
    self.order = project.stages.maximum(:order).to_i + 1
  end

  # overwrites papertrail to record script
  def object_attrs_for_paper_trail(attributes)
    super(attributes.merge('script' => script))
  end

  # DeployGroupsStage has no ids so the default dependent: :destroy fails
  def destroy_deploy_groups_stages
    DeployGroupsStage.where(stage_id: id).delete_all
  end
end

app/controllers/api/stages_controller.rb
class Api::StagesController < Api::BaseController
  include CurrentProject

  before_action :require_project

  def index
    render json: @project.stages
  end

  def clone
    new_stage = Stage.build_clone(stage_to_clone)
    new_stage.name = stage_name
    new_stage.deploy_groups = deploy_groups if deploy_groups.any?
    if new_stage.save
      render json: new_stage, status: 201
    else
      render json: new_stage.errors, status: 422
    end
  end

  private

  def stage_to_clone
    Stage.find_by_param!(params.require(:stage_id))
  end

  def stage_name
    params.fetch(:stage_name, "Copy of #{stage_to_clone.name}")
  end

  def deploy_group_ids
    params.fetch(:deploy_group_ids, [])
  end

  def deploy_groups
    DeployGroup.where(id: deploy_group_ids)
  end
end

app/controllers/stages_controller.rb
class StagesController < ApplicationController
  include CurrentProject
  include StagePermittedParams

  skip_around_action :login_user, if: :badge?

  before_action :authorize_project_deployer!, unless: :badge?
  before_action :authorize_project_admin!, except: [:index, :show]
  before_action :check_token, if: :badge?
  before_action :find_stage, only: [:show, :edit, :update, :destroy, :clone]

  def index
    @stages = @project.stages

    respond_to do |format|
      format.html
    end
  end

  def show
    respond_to do |format|
      format.html do
        @deploys = @stage.deploys.page(params[:page])
      end
      format.svg do
        badge =
          if deploy = @stage.last_successful_deploy
            "#{badge_safe(@stage.name)}-#{badge_safe(deploy.short_reference)}-green"
          else
            "#{badge_safe(@stage.name)}-None-red"
          end
        redirect_to "https://img.shields.io/badge/#{badge}.svg"
      end
    end
  end

  def new
    @stage = @project.stages.build(command_ids: Command.global.pluck(:id))
  end

  def create
    # Need to ensure project is already associated
    @stage = @project.stages.build
    @stage.attributes = stage_params

    if @stage.save
      redirect_to [@project, @stage]
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @stage.update_attributes(stage_params)
      redirect_to [@project, @stage]
    else
      render :edit
    end
  end

  def destroy
    @stage.soft_delete!
    redirect_to @project
  end

  def reorder
    Stage.reset_order(params[:stage_id])
    head :ok
  end

  def clone
    @stage = Stage.build_clone(@stage)
    render :new
  end

  private

  def badge_safe(string)
    CGI.escape(string).
      gsub('+', '%20').
      gsub(/-+/, '--')
  end

  def check_token
    unless params[:token] == Rails.application.config.samson.badge_token
      raise ActiveRecord::RecordNotFound
    end
  end

  def badge?
    action_name == 'show' && request.format == Mime::SVG
  end

  def stage_params
    params.require(:stage).permit(stage_permitted_params)
  end

  def find_stage
    @stage = current_project.stages.find_by_param!(params[:id])
  end
end

app/helpers/stages_helper.rb
module StagesHelper
  def edit_command_link(command)
    admin = current_user.admin? || current_user.admin_for?(command.project)
    edit_url = edit_admin_command_path(command)
    if command.global?
      title, url =
        if admin
          ["Edit global command", edit_url]
        else
          ["Global command, can only be edited via Admin UI", "#"]
        end
      link_to "", url, title: title, class: "edit-command glyphicon glyphicon-globe no-hover"
    elsif admin
      link_to "", edit_url, title: "Edit in admin UI", class: "edit-command glyphicon glyphicon-edit no-hover"
    end
  end

  def stage_lock_icon(stage)
    return unless stage.lock
    text =
      if stage.lock.warning?
        "#{warning_icon} Warning"
      else
        "#{lock_icon} Locked"
      end
    content_tag :span, text.html_safe, class: "label label-warning", title: stage.lock.summary
  end
end

app/views/stages/_fields.html.erb
<fieldset>
  <div class="form-group">
    <%= form.label :name, "Name", class: "col-lg-2 control-label" %>
    <div class="col-lg-4">
      <%= form.text_field :name, class: "form-control" %>
    </div>
  </div>

  <% if form.object.persisted? %>
    <div class="form-group">
      <%= form.label :permalink, "Permalink", class: "col-lg-2 control-label" %>
      <div class="col-lg-4">
        <%= form.text_field :permalink, class: "form-control" %>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :notify_email_address, "Email addresses", class: "col-lg-2 control-label" %>
    <div class="col-lg-4">
      <%= form.text_field :notify_email_address, class: "form-control" %>
      <span class="help-block">Enter the email addresses that should be notified of new deploys, separated by <code>;</code></span>
    </div>
  </div>

  <% if DeployGroup.enabled? %>
    <%= render 'deploy_groups/deploy_group_select', form: form %>
  <% else %>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <div class="checkbox">
          <%= form.label :production do %>
            <%= form.check_box :production %>
            Does this stage impact production servers?
          <% end %>
        </div>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <div class="checkbox">
        <%= form.label :no_code_deployed do %>
          <%= form.check_box :no_code_deployed %>
          <% details = "Bypass " + [("buddy check" if BuddyCheck.enabled?), "release tracking"].compact.to_sentence %>
          Does not deploy code <abbr title="<%= details %>">?</abbr>
        <% end %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <div class="checkbox">
        <%= form.label :confirm do %>
          <%= form.check_box :confirm %>
          Confirm before deployment
        <% end %>
      </div>
    </div>
  </div>

  <% if @project.releases.any? %>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <div class="checkbox">
          <%= form.label :deploy_on_release do %>
            <%= form.check_box :deploy_on_release %>
            Automatically deploy new releases
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</fieldset>

<%= render 'shared/commands', form: form %>

<fieldset>
  <legend>Dashboard</legend>
  <p>HTML that should be displayed on the stage page. No Javascript allowed.</p>

  <%= form.text_area :dashboard, class: "form-control", rows: 4 %>
</fieldset>

<fieldset>
  <legend>Email on automated deploy failure</legend>
  <div class="col-lg-offset-2">
    <p>When an automated deploy initially fails, send a email to:</p>

    <div class="form-group">
      <div class="col-lg-6 checkbox">
        <%= form.label :email_committers_on_automated_deploy_failure do %>
          <%= form.check_box :email_committers_on_automated_deploy_failure %>
          Committers in the diff to last successful deploy
        <% end %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-lg-6">
        <p>Addresses (comma separated):</p>
        <%= form.text_field :static_emails_on_automated_deploy_failure, class: "form-control" %>
      </div>
    </div>
  </div>
</fieldset>

<%= Samson::Hooks.render_views(:stage_form, self, form: form) %>

<fieldset>
  <legend>GitHub</legend>
  <div class="col-lg-6 checkbox col-lg-offset-2">
    <%= form.label :update_github_pull_requests do %>
      <%= form.check_box :update_github_pull_requests %>
      Update Pull Request after deployment
    <% end %>
  </div>
  <div class="col-lg-6 checkbox col-lg-offset-2">
    <%= form.label :use_github_deployment_api do %>
      <%= form.check_box :use_github_deployment_api %>
      Use GitHub Deployment API [beta]
    <% end %>
  </div>
</fieldset>

app/views/stages/_form.html.erb
<%= form_for [project, stage], html: { class: "form-horizontal" } do |form| %>
  <%= render 'shared/errors', object: stage %>

  <fieldset>
    <%= render 'stages/fields', form: form %>
  </fieldset>

  <hr>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <button type="submit" class="btn btn-default">Save</button>
    </div>
  </div>
<% end %>

app/views/stages/edit.html.erb
<% content_for(:page_title, "Editing #{@stage.name} (#{@project.name})") %>

<%= breadcrumb @project, @stage, "Edit" %>

<h1>Edit stage</h1>

<section>
  <%= render 'form', project: @project, stage: @stage %>
</section>

app/views/stages/index.html.erb
<h1>
  <%= link_to @project.name, @project %> Stages
</h1>


<section class="tabs">
  <ul id="stages" data-url="<%= reorder_project_stages_path(@project) %>" data-sortable="<%= admin_for_project? %>">
    <% @stages.each.with_index do |stage, index| %>
      <li class="stage-bar bar list-unstyled clearfix<%= ' sortable' if admin_for_project? %>" data-id="stage_id_<%= stage.id %>">
        <%= link_to stage.name, [@project, stage] %>
        <%= stage_lock_icon stage %>
        <div class="btn-group pull-right">
          <% if admin_for_project? %>
            <%= link_to "Clone", clone_project_stage_path(@project, stage), class: "btn btn-default" %>
          <% end %>
          <%= deploy_link @project, stage %>
        </div>
      </li>
    <% end %>
  </ul>

  <% if admin_for_project? %>
    <%= link_to "Add Stage", new_project_stage_path(@project), class: "btn btn-default" %>
  <% end %>

  <button id="error_message" class="messages btn btn-danger" disabled>
    Failed to save
  </button>

  <button id="success_message" class="messages btn btn-success" disabled>
    Saved
  </button>
</section>

app/views/stages/new.html.erb
<%= breadcrumb @project, "New Stage" %>

<section>
  <%= render 'form', project: @project, stage: @stage %>
</section>

app/views/stages/show.html.erb
<% content_for :page_title, @stage.global_name %>

<%= breadcrumb @project, @stage %>

<%= render @stage.lock if @stage.lock %>

<h1>
  <%= @stage.name %>
  <%= image_tag project_stage_path(@project, @stage, format: :svg, token: Rails.application.config.samson.badge_token), title: "Deploy badge" %>
</h1>

<section>
  <h2>Actions</h2>
  <div>
    <%= deploy_link @project, @stage %>

    <%= render "locks/button", lock: @stage.lock %>

    <% if admin_for_project? %>
      <%= link_to "Edit", edit_project_stage_path(@project, @stage), class: "btn btn-default" %>
      <%= link_to_delete_button([@project, @stage]) %>
    <% end %>

    <div class="pull-right">
      <%= link_to_history @stage %>
    </div>
  </div>

  <% if @stage.dashboard.present? %>
    <h2>Dashboard</h2>
    <div><%= sanitize @stage.dashboard, tags: Loofah::HTML5::WhiteList::ACCEPTABLE_ELEMENTS + %w[iframe] %></div>
  <% end %>

  <%= Samson::Hooks.render_views(:stage_show, self) %>

  <div id="script-section">
    <h2>Script</h2>
    <pre class="pre-command"><%= "set -ex\n" + @stage.script %></pre>
  </div>

  <% if groups = @stage.deploy_groups.sort_by(&:natural_order).to_a.presence %>
    <h2>Deploy groups</h2>
    <% groups.each do |group| %>
      <%= link_to group.name, group %>
    <% end %>
  <% end %>

  <h2>Recent deploys</h2>
  <table class="table">
    <thead>
      <tr>
        <th>When</th>
        <th>Who</th>
        <% unless @stage %>
          <th>Stage</th>
        <% end %>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
      <%= render partial: "/projects/deploy", collection: @deploys %>
    </tbody>
  </table>
  <%= paginate @deploys %>
</section>