config/routes.rb
Samson::Application.routes.draw do
  use_doorkeeper
  root to: 'projects#index'

  namespace :api do
    resources :deploys, only: [:index, :active_count] do
      collection do
        get :active_count
      end
    end

    resources :stages, only: [:index] do
      post :clone, to: 'stages#clone'
    end
  end

  resources :projects do
    resources :jobs, only: [:index, :new, :create, :show, :destroy]

    resources :macros, only: [:index, :new, :create, :edit, :update, :destroy] do
      member { post :execute }
    end

    resources :builds, only: [:show, :index, :new, :create, :edit, :update] do
      member do
        post :build_docker_image
      end
    end

    resources :deploys, only: [:index, :show, :destroy] do
      collection do
        get :active
      end

      member do
        post :buddy_check
        get :changeset
      end
    end

    resources :releases, only: [:show, :index, :new, :create]

    resources :stages do
      collection do
        patch :reorder
      end

      member do
        get :clone, to: 'stages#clone'
      end

      resources :deploys, only: [:new, :create] do
        collection do
          post :confirm
        end
      end
    end

    resource :changelog, only: [:show]
    resources :webhooks, only: [:index, :create, :destroy]
    resource :commit_statuses, only: [:show]
    resources :references, only: [:index]

    resources :users, only: [:index, :update]

    resources :project_roles, only: [:create]

    member do
      get :deploy_group_versions
    end
  end

  resources :streams, only: [:show]
  resources :locks, only: [:create, :destroy]

  resources :deploys, only: [:index] do
    collection do
      get :active
      get :recent
      get :search
    end
  end

  resources :deploy_groups, only: [:show]

  resource :profile, only: [:show, :update]

  resources :versions, only: [:index]

  get '/auth/github/callback', to: 'sessions#github'
  get '/auth/google/callback', to: 'sessions#google'
  post '/auth/ldap/callback', to: 'sessions#ldap'
  get '/auth/gitlab/callback', to: 'sessions#gitlab'
  get '/auth/failure', to: 'sessions#failure'

  get '/jobs/enabled', to: 'jobs#enabled', as: :enabled_jobs

  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'

  resources :csv_exports, only: [:index, :new, :create, :show]
  resources :stars, only: [:create, :destroy]
  resources :dashboards, only: [:show] do
    member do
      get :deploy_groups
    end
  end

  namespace :admin do
    resources :users, only: [:index, :show, :update, :destroy]
    resource :projects, only: [:show]
    resources :commands, except: [:show]
    resources :secrets, except: [:show]
    resources :environments, except: [:show]
    resources :deploy_groups do
      member do
        get :deploy_all
        post :deploy_all_now
      end
    end
  end

  namespace :integrations do
    post "/circleci/:token" => "circleci#create", as: :circleci_deploy
    post "/travis/:token" => "travis#create", as: :travis_deploy
    post "/semaphore/:token" => "semaphore#create", as: :semaphore_deploy
    post "/tddium/:token" => "tddium#create", as: :tddium_deploy
    post "/jenkins/:token" => "jenkins#create", as: :jenkins_deploy
    post "/buildkite/:token" => "buildkite#create", as: :buildkite_deploy
    post "/github/:token" => "github#create", as: :github_deploy
  end

  get '/ping', to: 'ping#show'

  resources :access_requests, only: [:new, :create]

  mount SseRailsEngine::Engine, at: '/streaming'
end

app/models/deploy_group.rb
class DeployGroup < ActiveRecord::Base
  include Permalinkable

  has_soft_deletion default_scope: true

  belongs_to :environment
  has_many :deploy_groups_stages
  has_many :stages, through: :deploy_groups_stages

  validates_presence_of :name, :environment_id
  validates_uniqueness_of :name, :env_value
  validates_format_of :env_value, with: /\A\w[-_:\w]*\w\z/
  before_validation :initialize_env_value, on: :create

  default_scope { order(:name) }

  after_save :touch_stages
  before_destroy :touch_stages
  after_destroy :destroy_deploy_groups_stages

  def self.enabled?
    ENV['DEPLOY_GROUP_FEATURE'].present?
  end

  def deploys
    Deploy.where(stage: stage_ids)
  end

  def long_name
    "#{name} (#{environment.name})"
  end

  def natural_order
    name.split(/(\d+)/).each_with_index.map { |x, i| i.odd? ? x.to_i : x }
  end

  private

  def permalink_base
    name
  end

  def touch_stages
    stages.update_all(updated_at: Time.now)
  end

  def initialize_env_value
    self.env_value = name.to_s.parameterize if env_value.blank?
  end

  # DeployGroupsStage has no ids so the default dependent: :destroy fails
  def destroy_deploy_groups_stages
    DeployGroupsStage.where(deploy_group_id: id).delete_all
  end
end

app/controllers/admin/deploy_groups_controller.rb
class Admin::DeployGroupsController < ApplicationController
  before_action :authorize_admin!
  before_action :authorize_super_admin!, only: [:create, :new, :update, :destroy, :deploy_all, :deploy_all_now, :edit]
  before_action :deploy_group, only: [:show, :edit, :update, :destroy, :deploy_all, :deploy_all_now]

  def index
    @deploy_groups = DeployGroup.all.sort_by(&:natural_order)
  end

  def show
  end

  def new
    @deploy_group = DeployGroup.new
    Samson::Hooks.fire(:edit_deploy_group, @deploy_group)
    render :edit
  end

  def create
    @deploy_group = DeployGroup.create(deploy_group_params)
    if @deploy_group.persisted?
      flash[:notice] = "Successfully created deploy group: #{@deploy_group.name}"
      redirect_to action: :index
    else
      render :edit
    end
  end

  def edit
    Samson::Hooks.fire(:edit_deploy_group, @deploy_group)
  end

  def update
    if deploy_group.update_attributes(deploy_group_params)
      flash[:notice] = "Successfully saved deploy group: #{deploy_group.name}"
      redirect_to action: :index
    else
      render :edit
    end
  end

  def destroy
    if deploy_group.deploy_groups_stages.empty?
      deploy_group.soft_delete!
      flash[:notice] = "Successfully deleted deploy group: #{deploy_group.name}"
      redirect_to action: :index
    else
      flash[:error] = "Deploy group is still in use."
      redirect_to [:admin, deploy_group]
    end
  end

  def deploy_all
    @stages = Project.all.flat_map do |project|
      environment = Environment.find(params[:environment_id]) if params[:environment_id]

      stages = stages_in_same_environment(project, environment)
      next unless deploy = stages.map(&:last_successful_deploy).compact.sort_by(&:created_at).last
      stages.map { |s| [s, deploy] }
    end.compact
  end

  def deploy_all_now
    deploys = params.require(:stages).map do |stage|
      stage_id, reference = stage.split("-", 2)
      stage = Stage.find(stage_id)
      stage = new_stage_with_group(stage) unless only_to_current_group?(stage)
      deploy_service = DeployService.new(current_user)
      deploy_service.deploy!(stage, reference: reference)
    end
    redirect_to deploys_path(ids: deploys.map(&:id))
  end

  private

  def only_to_current_group?(stage)
    stage.deploy_groups.map(&:id) == [deploy_group.id]
  end

  def stages_in_same_environment(project, environment)
    environment ||= deploy_group.environment
    stages = project.stages.select do |stage|
      stage.script.include?("$DEPLOY_GROUPS") && # is dynamic
        stage.deploy_groups.where(environment: environment).exists? # is made to go to this environment
    end
    stages.sort_by { |stage| only_to_current_group?(stage) ? 0 : 1 }
  end

  def new_stage_with_group(stage)
    stage = Stage.build_clone(stage)
    stage.deploy_groups << deploy_group
    stage.name = deploy_group.name
    stage.name << " -- copy #{SecureRandom.hex(4)}" if stage.project.stages.where(name: stage.name).exists?
    stage.save!
    stage
  end

  def deploy_group_params
    params.require(:deploy_group).permit(*allowed_deploy_group_params)
  end

  def allowed_deploy_group_params
    ([:name, :environment_id, :env_value, :vault_instance] + Samson::Hooks.fire(:deploy_group_permitted_params)).freeze
  end

  def deploy_group
    @deploy_group ||= DeployGroup.find_by_param!(params[:id])
  end
end

app/controllers/deploy_groups_controller.rb
class DeployGroupsController < ApplicationController
  before_action :find_deploy_group

  def show
    respond_to do |format|
      format.html do
        @deploys = @deploy_group.deploys.page(params[:page])
      end
      format.json do
        deploys = @deploy_group.deploys.successful.page(params[:page]).as_json(include: :project, methods: :url)
        render json: { deploys:  deploys }
      end
    end
  end

  private

  def find_deploy_group
    @deploy_group = DeployGroup.find_by_param!(params[:id])
  end
end

app/views/admin/deploy_groups/_environment_selector.html.erb
<%= form_tag '?', method: :get do %>
  Environment: <%= select_tag :environment_id, options_for_select(environments.map { |e| [e.name, e.id] }, params[:environment_id] || @deploy_group.environment_id) %>
<% end %>

<script>
  $(function(){
    // when environment selector is changed, reload the page
    $('#environment_id').change(function(){
      $(this.form).submit();
    });
  });
</script>

app/views/admin/deploy_groups/_fields.html.erb
<fieldset>
  <div class="form-group">
    <%= form.label :name, "Name", class: "col-lg-2 control-label" %>
    <div class="col-lg-4">
      <%= form.text_field :name, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :env_value, "Value in $DEPLOY_GROUPS", class: "col-lg-2 control-label" %>
    <div class="col-lg-4">
      <%= form.text_field :env_value, class: "form-control" %>
    </div>
  </div>

  <% if SecretStorage.backend == SecretStorage::HashicorpVault %>
    <div class="form-group">
      <%= form.label :vault_instance, "Vault Instance", class: "col-lg-2 control-label" %>
      <div class="col-lg-4">
        <%= form.select(:vault_instance, options_for_select(VaultClient.available_instances, @deploy_group.vault_instance), {}, class: "form-control", required: true) %>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, "Environment", class: "col-lg-2 control-label" %>
    <div class="col-lg-4">
      <%= form.collection_select(:environment_id, environments, :id, :name, {}, { class: 'form-control' }) %>
    </div>
  </div>

  <%= Samson::Hooks.render_views(:deploy_group_form, self, form: form) %>
</fieldset>

app/views/admin/deploy_groups/deploy_all.html.erb
<h1>Deploy to <%= @deploy_group.name %></h1>

<%= render 'environment_selector' %>

<%= form_tag deploy_all_now_admin_deploy_group_path(@deploy_group) do %>
  <section class="clearfix">
    <div class="table table-hover table-condensed">
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>Project</th>
            <th>Stage</th>
            <th>Reference</th>
          </tr>
        </thead>

        <tbody>
          <% @stages.each do |stage, deploy| %>
            <tr>
              <td><%= check_box_tag 'stages[]', "#{stage.id}-#{deploy.reference}" %></td>
              <td><%= link_to stage.project.name, stage.project %></td>
              <td><%= link_to stage.name, [stage.project, stage] %></td>
              <td><%= deploy.reference %> (<%= time_ago_in_words deploy.created_at %> ago)</td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class="admin-actions">
      <div class="pull-right">
        <%= submit_tag "Deploy", class: "btn btn-default" %>
      </div>
    </div>
  </section>
<% end %>

app/views/admin/deploy_groups/edit.html.erb
<h1><%= @deploy_group.new_record? ? 'New' : 'Edit' %> Deploy Group <%= link_to_if @deploy_group.id, @deploy_group.name, [:admin, @deploy_group] %></h1>

<section>
  <%= form_for [:admin, @deploy_group], html: { class: "form-horizontal" } do |form| %>
    <%= render 'shared/errors', object: @deploy_group %>

    <%= render 'admin/deploy_groups/fields', form: form %>

    <hr>

    <div class="form-group">
      <div class="col-lg-offset-2 col-lg-10">
        <%= form.submit "Save", class: 'btn btn-default' %>
        <%= link_to_delete([:admin, @deploy_group]) %>
      </div>
    </div>
  <% end %>
</section>

app/views/admin/deploy_groups/index.html.erb
<h1>Deploy Groups</h1>

<section class="clearfix tabs">
  <div class="table table-hover table-condensed">
    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Environment</th>
          <th>$DEPLOY_GROUPS</th>
          <%= Samson::Hooks.render_views(:deploy_group_table_header, self) %>
          <th>Actions</th>
        </tr>
      </thead>

      <tbody>
        <% @deploy_groups.each do |deploy_group| %>
          <tr>
            <td><%= deploy_group.name%></td>
            <td><%= deploy_group.environment.name %></td>
            <td><%= deploy_group.env_value %></td>
            <%= Samson::Hooks.render_views(:deploy_group_table_cell, self, deploy_group: deploy_group) %>
            <td>
              <%= link_to "Show", admin_deploy_group_path(deploy_group) %>
              |
              <%= link_to "Edit", edit_admin_deploy_group_path(deploy_group) %>
              |
              <%= link_to_delete([:admin, deploy_group]) %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="admin-actions">
    <div class="pull-right">
      <%= link_to "New", new_admin_deploy_group_path, class: "btn btn-default" %>
    </div>
  </div>
</section>

app/views/admin/deploy_groups/show.html.erb
<h1><%= @deploy_group.name %></h1>

<section class="form-horizontal">
  <div class="form-group">
    <label class="col-lg-2 control-label">$DEPLOY_GROUPS value</label>
    <div class="col-lg-4">
      <p class="form-control-static"><%= @deploy_group.env_value %></p>
    </div>
  </div>

  <div class="form-group">
    <label class="col-lg-2 control-label">Environment</label>
    <div class="col-lg-4">
      <p class="form-control-static"><%= @deploy_group.environment.name %></p>
    </div>
  </div>

  <div class="form-group">
    <label class="col-lg-2 control-label">Used by</label>
    <div class="col-lg-4">
      <p class="form-control-static">
        <% @deploy_group.deploy_groups_stages.group_by { |dgs| dgs.stage.project }.each do |project, dgs_group| %>
          <h3><%= link_to project.name, project %></h3>
          <% dgs_group.each do |dgs| %>
            <%= link_to dgs.stage.name, [dgs.stage.project, dgs.stage] %><br/>
          <% end %>
        <% end %>
      </p>
    </div>
  </div>

  <%= Samson::Hooks.render_views(:deploy_group_show, self) %>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= link_to "Edit", edit_admin_deploy_group_path(@deploy_group), class: "btn btn-primary" %>
      <%= link_to "Deploy all projects", deploy_all_admin_deploy_group_path(@deploy_group), class: "btn btn-default" if DeployGroup.enabled? %>
      <%= link_to "Back", admin_deploy_groups_path, class: "btn btn-default" %>
    </div>
  </div>
</section>